### ISSUE TITLE
Adding more LLM APIs as runners / extending

### ISSUE THREAD

**Issue by t-schn** [microsoft/sammo#12]
Right now, only OpenAI API compatible models are supported. [Possible other LLMs](https://python.langchain.com/docs/integrations/llms/)

Ideas:
- Write wrapper around LangChain class
- Tutorial to show how to implement custom Runner class.

**Comment by tfk12** [comment]
Good suggestion! Is this repo dead?

**Comment by t-schn** [comment]
With the newest release, we have more runners added.
Closing this for now.

#46

**Comment by t-schn** [comment]
With the newest release, we have more runners added.
Closing this for now.

#46
