### ISSUE TITLE
Change from 4 number version to 3 number

### ISSUE THREAD

**Issue by pbourke** [microsoft/sammo#22]
Currently our version numbers look like "0.1.0.6". This proposal is to make the next version number "0.1.1". 3 number versions are conventional for Python, and are a bit easier to work with using some tooling such as `poetry version` (not a major issue).

I think for a project of this size, we'll be okay to just use semantic versioning with conventional major, minor and patch releases.

**Comment by t-schn** [comment]
I agree, let's drop the fourth.
