### ISSUE TITLE
How to easily create an Azure OpenAI runner?

### ISSUE THREAD

**Issue by Elizabeth819** [microsoft/sammo#44]
Could you provide a way of creating OpenAIChat() using AOAI api_base and api_key, as MSFT employee it is hard to use our own OAI key to do experiments, thanks!

**Comment by pbourke** [comment]
The `AzureChat` runner extends `OpenAIChat` to mix in Azure OpenAI capabilities. Here's an example for configuring one. 

Note that the `deployment` from AOAI goes in both the `model_id` and `api_config.deployment_id` when creating the runner.

```python
from sammo.runners import AzureChat

# Azure-specific settings
deployment_id = ""
endpoint_url = ""   # should have trailing /
api_key = ""
api_version = "2024-06-01"

runner = AzureChat(
    model_id=deployment_id,
    api_config={
        "endpoint": endpoint_url,
        "api_key": api_key,
        "deployment_id": deployment_id,
        "api_version": api_version
    }
)

result = await runner.generate_text("Q: solve this problem: 20 * 7 =?\n\nA: Let's think step by step, make a plan and answer the question")
print(result.value)

```

**Comment by t-schn** [comment]
Added to [documentation](https://microsoft.github.io/sammo/tutorials/special_topics/0_llm_apis.html)
