### ISSUE TITLE
Add guidelines/workflow for contributors

### ISSUE THREAD

**Issue by onkarbhardwaj** [microsoft/sammo#5]
Request to add guidelines/workflow somewhere in README or CONTRIBUTING.md - For example, how to replicate the environment, pre-commit hooks, formatting/linting (e.g., `black`/`flake8`) that's expected for a PR to be accepted.

**Comment by pbourke** [comment]
Thanks for opening this issue. I'm setting up our initial pre-commit hooks and have created the CONTRIBUTING.md file as part of that PR. There is more to be added to the file, but it does mention installation of pre-commit hooks. `black` will be run from a hook.

I anticipate adding others (such as `flake8` as you mention)

**Comment by pbourke** [comment]
Reopening this issue to track ongoing work for contributor guidelines
