### ISSUE TITLE
Attribute Error using AzureEmbedding class of SAMMO

### ISSUE THREAD

**Issue by Nithyashree-coder** [microsoft/sammo#55]
For using RAG with SAMMO, I am using Azure Openai models. Below is the example of the initialization of Runner and Embedder. 
![Image](https://github.com/user-attachments/assets/d5ccb481-838e-456c-9f10-68d455d9d96c)

Below is the metaprompt I have used. 
![Image](https://github.com/user-attachments/assets/d77604b6-6c7a-4ac3-aac2-850151d3558a)

While calling EmbeddingFewShowShotExamples in code, I am getting the below error:
![Image](https://github.com/user-attachments/assets/98547dcf-a5d1-4573-8f29-44131763ebca)

Even If I instantiate AzureEmbedding class with cache = None, still this error persists.
Also I tried using SqlLiteDict for AzureEmbedding and PersistentDict for AzureChat as per documentation
![Image](https://github.com/user-attachments/assets/4a3600e4-96e3-461c-92df-bf40ad2a2a0b)

But still I am getting the same error "**Error: AttributeError: 'AzureEmbedding' object has no attribute '_embeddings_cache**'"

**Comment by t-schn** [comment]
@Nithyashree-coder: Happy to look into this, but can you create a minimal reproducible example and paste the code here?

**Comment by Nithyashree-coder** [comment]
@t-schn , Sure. I had reffered to [rag_tuning_sammo.py ](https://github.com/microsoft/sammo/blob/main/examples/paper_rag/rag_tuning_sammo.py) while coding. I was not getting any idea on this because there was no documentation on RAG using SAMMO. It would be great if the team shared some documentation on rag using SAMMO. I couldn't construct a minimalistic version of the code. To reproduce the error, you can check [Sammo_Rag](https://github.com/Nithyashree-coder/Sammo_Rag) repository and run the [main.py](https://github.com/Nithyashree-coder/Sammo_Rag/blob/main/main.py) code.

**Comment by t-schn** [comment]
@Nithyashree-coder: Thanks a lot! I was able to reproduce the error and tracked it down to an issue from a parent method not being called due to multi inheritance. See #58 for the fix. Let me know if you keep having issues!

**Comment by Nithyashree-coder** [comment]
Thank you so much! I downloaded the latest version of sammo and I am able to run the code.
