### ISSUE TITLE
Using Python 3.12+?

### ISSUE THREAD

**Issue by kmhansen** [microsoft/sammo#68]
What's the reason that you don't allow install of Sammo for Python 3.12 and above? Could this be changed?

With Python 3.12.8, I get:

(venv) PS C:\> pip install sammo
ERROR: Ignored the following versions that require a different python version: 0.1.0.1 Requires-Python >=3.10,<3.12; 0.1.0.2 Requires-Python >=3.10,<3.12; 0.1.0.3 Requires-Python >=3.10,<3.12; 0.1.0.4 Requires-Python >=3.11,<3.12; 0.1.0.5 Requires-Python >=3.11,<3.12; 0.1.0.6 Requires-Python >=3.11,<3.12; 0.1.4 Requires-Python >=3.11,<3.12; 0.1.6 Requires-Python <3.12,>=3.11; 0.1.7 Requires-Python <3.12,>=3.9; 0.1.8 Requires-Python <3.12,>=3.9; 0.2.0 Requires-Python <3.12,>=3.9; 0.2.1 Requires-Python <3.12,>=3.9; 0.2.4 Requires-Python <3.12,>=3.9; 0.2.6 Requires-Python <3.12,>=3.9; 0.2.7 Requires-Python <3.12,>=3.9; 0.3.1 Requires-Python <3.12,>=3.9
ERROR: Could not find a version that satisfies the requirement sammo (from versions: none)
ERROR: No matching distribution found for sammo

(venv) PS C:\> python --version    
Python 3.12.8

**Comment by t-schn** [comment]
@kmhansen: It was purely to make sure dependencies don't break while upgrading. I tested and added Python 3.12 support with the newest release.
