### ISSUE TITLE
How to save and load the best prompt?

### ISSUE THREAD

**Issue by dpernes** [microsoft/sammo#69]
Hi,

Thank you for developing this really nice tool. I'm having trouble saving and loading the best prompt of the optimizer.

To save it, I was doing:
```
with open("best_prompt.json", "w") as f:
    json.dump(prompt_optimizer.best_prompt.to_json(), f)
```
And then to load it:
```
with open("best_prompt.json", "w") as f:
   best_prompt = Output.from_json(json.load(f))
```
But this raises `TypeError: Object.from_json() got an unexpected keyword argument '_type'`. I tried dropping the `'_type'` key from the dict but that raises another error. Thank you in advance for your help.

**Comment by t-schn** [comment]
Hi,

the json loading isn't even implemented at the moment -- only json saving. I would instead use the save() and load() method of the optimizer, or write your own serialization function like here: https://github.com/microsoft/sammo/blob/7ad76482f5776ed83f608f39ef9be4b96cab8329/sammo/search.py#L104-L114
