### ISSUE TITLE
Bug in quickstart example in github pages

### ISSUE THREAD

**Issue by onkarbhardwaj** [microsoft/sammo#7]
`CACHE_FILE` variable has not been defined in the quickstart [example](https://microsoft.github.io/sammo/tutorials/0_quickstart.html) prior to its use.

<img width="329" alt="image" src="https://github.com/microsoft/sammo/assets/13560220/b978f350-bdef-4d76-b729-af25ea706c4a">

**Comment by t-schn** [comment]
It actually is defined in the header of the jupyter notebook corresponding to the quickstart page, but is hidden for the documentation. I changed it to be based on environment variables - hope that clears up the confusion!

**Comment by t-schn** [comment]
It actually is defined in the header of the jupyter notebook corresponding to the quickstart page, but is hidden for the documentation. I changed it to be based on environment variables - hope that clears up the confusion!
